import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const CATEGORY_KEYWORDS: Record<string, string[]> = {
  Motor: ['motor', 'car', 'vehicle', 'automobile', 'auto', 'driving', 'third party', 'comprehensive', 'road', 'accident', 'collision', 'theft', 'transport'],
  Property: ['property', 'home', 'house', 'building', 'contents', 'fire', 'flood', 'burglary', 'landlord', 'tenant', 'office', 'shop', 'real estate', 'electronic', 'computer'],
  Health: ['health', 'medical', 'hospital', 'doctor', 'illness', 'sickness', 'treatment', 'surgery', 'medicine', 'healthcare', 'hmo', 'outpatient', 'inpatient', 'maternity'],
  Life: ['life', 'death', 'funeral', 'beneficiary', 'family', 'protection', 'term', 'whole life', 'endowment', 'savings', 'employer', 'employee', 'group life'],
  Marine: ['marine', 'cargo', 'ship', 'boat', 'sea', 'ocean', 'freight', 'import', 'export', 'goods in transit', 'water', 'vessel', 'shipping', 'form M'],
  Engineering: ['engineering', 'machinery', 'equipment', 'construction', 'contractor', 'erection', 'plant', 'industrial', 'factory', 'breakdown', 'civil'],
  Financial: ['financial', 'money', 'fidelity', 'bond', 'fraud', 'professional', 'indemnity', 'liability', 'directors', 'officers', 'surety', 'guarantee', 'performance', 'advance payment'],
  Liability: ['liability', 'public', 'employer', 'workmen', 'compensation', 'accident', 'injury', 'third party', 'legal', 'professional', 'indemnity'],
  Agriculture: ['agriculture', 'farm', 'crop', 'livestock', 'cattle', 'poultry', 'fish', 'harvest', 'farmer', 'rural'],
  Travel: ['travel', 'holiday', 'vacation', 'trip', 'abroad', 'flight', 'luggage', 'passport', 'visa', 'overseas', 'international', 'tourist', 'schengen'],
};

async function main() {
  const adminPassword = await bcrypt.hash('Admin@123456', 10);
  await prisma.user.upsert({
    where: { email: 'admin@africover247.com' },
    update: {},
    create: {
      email: 'admin@africover247.com',
      firstName: 'AfriCover',
      lastName: 'Admin',
      passwordHash: adminPassword,
      role: 'admin',
      emailVerified: true,
      phone: '08000000000',
    },
  });

  const customerPassword = await bcrypt.hash('Customer@123456', 10);
  await prisma.user.upsert({
    where: { email: 'test@africover247.com' },
    update: {},
    create: {
      email: 'test@africover247.com',
      firstName: 'Test',
      lastName: 'Customer',
      passwordHash: customerPassword,
      role: 'customer',
      emailVerified: true,
      phone: '08012345678',
    },
  });

  const products = [
    {
      name: 'Motor Insurance — 3rd Party (Private Car)',
      category: 'Motor',
      description: 'Compulsory third-party motor insurance for private cars on Nigerian roads. Covers damage or injury caused to other people and their property. Required by law before driving on public roads in Nigeria.',
      pricingType: 'fixed' as const,
      premiumAmount: 15000,
      coverageHighlights: 'Third-party bodily injury\nThird-party property damage\nLegal liability cover',
      exclusions: 'Own vehicle damage\nTheft of own vehicle\nPersonal accident to driver\nDrunk driving incidents',
      requiredDocuments: 'Vehicle registration document\nValid driver\'s licence',
      assetFields: [
        { key: 'vehicleRegNumber', label: 'Vehicle Registration Number', type: 'text', required: true },
        { key: 'vehicleMake', label: 'Vehicle Make & Model', type: 'text', required: true },
        { key: 'vehicleYear', label: 'Year of Manufacture', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['motor', 'car', 'third party', 'tpft', 'private car', 'vehicle', 'automobile'],
    },
    {
      name: 'Motor Insurance — 3rd Party (Commercial Motor)',
      category: 'Motor',
      description: 'Compulsory third-party motor insurance for commercial vehicles including goods vans and buses. Covers liability to third parties arising from the use of the vehicle on public roads.',
      pricingType: 'fixed' as const,
      premiumAmount: 20000,
      coverageHighlights: 'Third-party bodily injury\nThird-party property damage\nLegal liability cover\nCommercial vehicle endorsement',
      exclusions: 'Own vehicle damage\nCargo in transit\nDrunk driving incidents\nUnauthorised use',
      requiredDocuments: 'Vehicle registration document\nValid driver\'s licence\nRoad worthiness certificate',
      assetFields: [
        { key: 'vehicleRegNumber', label: 'Vehicle Registration Number', type: 'text', required: true },
        { key: 'vehicleMake', label: 'Vehicle Make & Model', type: 'text', required: true },
        { key: 'vehicleYear', label: 'Year of Manufacture', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['motor', 'commercial', 'third party', 'goods vehicle', 'bus', 'van', 'truck'],
    },
    {
      name: 'Motor Comprehensive Insurance',
      category: 'Motor',
      description: 'Full comprehensive motor insurance covering own vehicle damage, theft, fire, and third-party liability. The most complete motor cover available in Nigeria. Premium is 5% of the vehicle\'s current market value.',
      pricingType: 'calculable' as const,
      rate: 0.05,
      calculationBasis: 'vehicle market value',
      coverageHighlights: 'Own vehicle damage\nTheft and attempted theft\nFire damage\nThird-party bodily injury\nThird-party property damage\nFlood and storm damage',
      exclusions: 'Wear and tear\nMechanical breakdown\nDrunk driving\nUnlicensed drivers\nRacing or speed testing',
      requiredDocuments: 'Vehicle registration document\nValid driver\'s licence\nVehicle valuation report',
      assetFields: [
        { key: 'vehicleValue', label: 'Vehicle Market Value (₦)', type: 'number', required: true, hint: 'Current market value of your vehicle' },
        { key: 'vehicleRegNumber', label: 'Vehicle Registration Number', type: 'text', required: true },
        { key: 'vehicleMake', label: 'Vehicle Make & Model', type: 'text', required: true },
        { key: 'vehicleYear', label: 'Year of Manufacture', type: 'text', required: true },
        { key: 'vehicleColor', label: 'Vehicle Colour', type: 'text', required: false },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['motor', 'comprehensive', 'car', 'vehicle', 'full cover', 'own damage', 'theft', 'fire'],
    },
    {
      name: 'Fire & Special Perils Insurance',
      category: 'Property',
      description: 'Protects your buildings, machinery, and contents from sudden and accidental physical damage caused by fire and a designated list of extra natural or man-made disasters such as storms, floods, and explosions.',
      pricingType: 'quote_based' as const,
      rateMin: 0.002,
      rateMax: 0.005,
      coverageHighlights: 'Fire and explosion damage\nStorm and flood damage\nImpact damage\nMalicious damage\nBush fire\nAircraft damage',
      exclusions: 'War and terrorism\nNuclear risks\nWear and tear\nGovernment action\nTheft (covered separately)',
      requiredDocuments: 'Property valuation report\nBuilding plan or description\nProof of ownership',
      assetFields: [
        { key: 'propertyAddress', label: 'Property Address', type: 'text', required: true },
        { key: 'propertyType', label: 'Property Type', type: 'select', options: ['Residential Building', 'Commercial Building', 'Industrial Building', 'Warehouse', 'Office'], required: true },
        { key: 'buildingValue', label: 'Building Replacement Value (₦)', type: 'number', required: true },
        { key: 'contentsValue', label: 'Contents Value (₦)', type: 'number', required: false },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['fire', 'property', 'building', 'flood', 'explosion', 'storm', 'perils', 'house', 'office'],
    },
    {
      name: 'Burglary / Housebreaking Insurance',
      category: 'Property',
      description: 'Covers damage to your house and contents against fire, storms, or theft. Also covers damage to property caused during an attempted theft or break-in.',
      pricingType: 'quote_based' as const,
      rateMin: 0.0025,
      rateMax: 0.0045,
      coverageHighlights: 'Theft and burglary\nDamage during break-in\nContents replacement\nLocks and security replacement',
      exclusions: 'Theft without forcible entry\nTheft by household members\nJewellery and cash limits apply\nUnoccupied premises',
      requiredDocuments: 'Inventory of insured contents\nProof of ownership',
      assetFields: [
        { key: 'propertyAddress', label: 'Property Address', type: 'text', required: true },
        { key: 'contentsValue', label: 'Contents/Property Value (₦)', type: 'number', required: true },
        { key: 'securityMeasures', label: 'Security Measures in Place', type: 'text', required: false, hint: 'e.g. CCTV, security guard, burglar alarm' },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['burglary', 'theft', 'housebreaking', 'break in', 'robbery', 'contents', 'property', 'home', 'house'],
    },
    {
      name: 'Computer / Electronic Equipment Insurance',
      category: 'Property',
      description: 'All-risk insurance protecting your hardware, systems, and data from sudden, unexpected physical loss or damage. Covers computers, servers, electronic equipment, and related peripherals.',
      pricingType: 'quote_based' as const,
      rateMin: 0.0035,
      rateMax: 0.0065,
      coverageHighlights: 'Accidental damage\nTheft and attempted theft\nElectrical surge damage\nMalicious damage\nFire and flood\nData recovery costs',
      exclusions: 'Wear and tear\nSoftware losses\nVirus damage\nWarranty defects\nGradual deterioration',
      requiredDocuments: 'Equipment inventory and serial numbers\nPurchase receipts or valuation',
      assetFields: [
        { key: 'equipmentValue', label: 'Total Equipment Replacement Value (₦)', type: 'number', required: true },
        { key: 'equipmentDescription', label: 'Equipment Description', type: 'text', required: true, hint: 'e.g. 10 laptops, 2 servers, network equipment' },
        { key: 'location', label: 'Location of Equipment', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['computer', 'electronic', 'equipment', 'laptop', 'server', 'IT', 'technology', 'hardware'],
    },
    {
      name: 'Plant All Risk / Machinery Breakdown Insurance',
      category: 'Engineering',
      description: 'Specialized engineering policies protecting industrial, construction, and commercial equipment. Plant All Risk covers external accidental damage (fire, theft), while Machinery Breakdown covers internal mechanical or electrical failures such as short circuits or design faults.',
      pricingType: 'quote_based' as const,
      rateMin: 0.007,
      rateMax: 0.012,
      coverageHighlights: 'Accidental external damage\nMechanical breakdown\nElectrical failure\nTheft of machinery\nFire and explosion\nOperator error',
      exclusions: 'Wear and tear\nConsumable parts\nExperimental machinery\nWar and terrorism\nIntentional damage',
      requiredDocuments: 'Machinery list with values\nMaintenance records\nInstallation certificates',
      assetFields: [
        { key: 'plantValue', label: 'Plant / Machinery Replacement Value (₦)', type: 'number', required: true },
        { key: 'plantDescription', label: 'Plant / Machinery Description', type: 'text', required: true },
        { key: 'industry', label: 'Industry / Sector', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['plant', 'machinery', 'engineering', 'industrial', 'factory', 'equipment', 'breakdown', 'mechanical'],
    },
    {
      name: "Contractors' All Risk Insurance",
      category: 'Engineering',
      description: 'Non-life policy protecting building and civil engineering projects from sudden physical damage, material losses, and third-party injury or property claims. Covers both permanent and temporary works until the project is completed or handed over.',
      pricingType: 'quote_based' as const,
      rateMin: 0.0035,
      rateMax: 0.0065,
      coverageHighlights: 'Physical damage to works\nThird-party liability\nTemporary works cover\nPlant and equipment on site\nRemoval of debris',
      exclusions: 'Design defects\nWear and tear\nPenalties for delay\nWar and terrorism\nNuclear risks',
      requiredDocuments: 'Contract documents\nProject value\nSite plan\nCompletion timeline',
      assetFields: [
        { key: 'contractValue', label: 'Contract / Project Value (₦)', type: 'number', required: true },
        { key: 'projectDescription', label: 'Project Description', type: 'text', required: true },
        { key: 'projectDuration', label: 'Project Duration (months)', type: 'text', required: true },
        { key: 'projectLocation', label: 'Project Location', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['contractor', 'construction', 'building', 'civil engineering', 'project', 'site', 'works'],
    },
    {
      name: 'Marine Cargo Insurance',
      category: 'Marine',
      description: 'Protects cargo, ships, and transport terminals against loss, damage, or theft while in transit. In Nigeria, a marine cargo insurance certificate is legally required when importing goods to process your Form M and clear shipments at Lagos ports.',
      pricingType: 'quote_based' as const,
      rateMin: 0.0035,
      rateMax: 0.006,
      coverageHighlights: 'Loss or damage in transit\nTheft and piracy\nFire and explosion\nJettison\nWeather damage\nPort handling damage',
      exclusions: 'Inherent vice\nWar and strikes (unless endorsed)\nDelay losses\nInsolvency of carrier\nWear and tear',
      requiredDocuments: 'Commercial invoice\nBill of lading\nPacking list\nForm M number',
      assetFields: [
        { key: 'cargoValue', label: 'Cargo Value (₦)', type: 'number', required: true },
        { key: 'cargoDescription', label: 'Cargo Description', type: 'text', required: true },
        { key: 'origin', label: 'Country of Origin', type: 'text', required: true },
        { key: 'destination', label: 'Destination Port', type: 'text', required: true },
        { key: 'shippingMethod', label: 'Mode of Transport', type: 'select', options: ['Sea freight', 'Air freight', 'Road', 'Water', 'Multimodal'], required: true },
      ],
      durationMonths: 1,
      isActive: true,
      keywords: ['marine', 'cargo', 'shipping', 'import', 'export', 'sea freight', 'form M', 'transit', 'goods'],
    },
    {
      name: 'Professional Indemnity Insurance',
      category: 'Liability',
      description: 'Protects professionals if a client claims their professional advice, service, or design caused a financial loss. Essential for consultants, accountants, lawyers, engineers, and other service professionals.',
      pricingType: 'quote_based' as const,
      rateMin: 0.005,
      rateMax: 0.01,
      coverageHighlights: 'Negligence claims\nProfessional errors and omissions\nBreach of duty\nDefamation\nLoss of documents\nLegal defence costs',
      exclusions: 'Fraud and dishonesty\nCriminal acts\nKnown circumstances at inception\nWar and terrorism\nInsolvency',
      requiredDocuments: 'Professional qualifications\nBusiness registration\nAnnual fee income\nClaims history',
      assetFields: [
        { key: 'profession', label: 'Profession / Business Type', type: 'text', required: true },
        { key: 'annualFeeIncome', label: 'Annual Fee Income (₦)', type: 'number', required: true },
        { key: 'coverLimit', label: 'Indemnity Limit Required (₦)', type: 'number', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['professional indemnity', 'consultant', 'lawyer', 'accountant', 'engineer', 'advice', 'liability', 'negligence'],
    },
    {
      name: 'Public / Product Liability Insurance',
      category: 'Liability',
      description: 'Protects businesses from third-party claims involving death, bodily injury, illness, or property damage. Public liability covers accidents during business operations; product liability covers harm caused by goods you sell, supply, or manufacture.',
      pricingType: 'quote_based' as const,
      rateMin: 0.003,
      rateMax: 0.005,
      coverageHighlights: 'Third-party bodily injury\nThird-party property damage\nProduct defect claims\nLegal defence costs\nMedical expenses',
      exclusions: 'Employee injuries (covered by Workmen\'s Compensation)\nContractual liability\nPollution\nWar and terrorism\nIntentional acts',
      requiredDocuments: 'Business registration\nAnnual turnover\nBusiness description\nPremises details',
      assetFields: [
        { key: 'businessType', label: 'Business Type / Industry', type: 'text', required: true },
        { key: 'annualTurnover', label: 'Annual Turnover (₦)', type: 'number', required: true },
        { key: 'coverLimit', label: 'Liability Limit Required (₦)', type: 'number', required: true },
        { key: 'numberOfEmployees', label: 'Number of Employees', type: 'text', required: false },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['public liability', 'product liability', 'business', 'third party', 'injury', 'customer', 'shop', 'premises'],
    },
    {
      name: 'Fidelity Guaranty Insurance',
      category: 'Financial',
      description: 'Protects businesses from direct financial losses caused by employee fraud, theft, forgery, or dishonesty. Reimburses an employer for stolen money, stock, or property when an insider breaks a trusted financial or administrative duty.',
      pricingType: 'quote_based' as const,
      rateMin: null,
      rateMax: null,
      coverageHighlights: 'Employee fraud and theft\nForgery and alteration\nComputer fraud\nFunds transfer fraud\nStock and inventory theft',
      exclusions: 'Known dishonest employees\nThird-party fraud\nWar and terrorism\nTrading losses\nAccounting errors',
      requiredDocuments: 'Business registration\nList of employees to be covered\nAnnual payroll\nFinancial controls description',
      assetFields: [
        { key: 'numberOfEmployees', label: 'Number of Employees to Cover', type: 'text', required: true },
        { key: 'coverLimit', label: 'Cover Limit Per Employee (₦)', type: 'number', required: true },
        { key: 'businessType', label: 'Business Type', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['fidelity', 'employee fraud', 'theft', 'dishonesty', 'forgery', 'financial', 'business', 'staff'],
    },
    {
      name: 'Money Insurance',
      category: 'Financial',
      description: 'Protects businesses and organizations against accidental loss, theft, robbery, or destruction of cash, bank notes, cheques, and postal orders. Covers funds while in transit, inside a locked safe, or in the personal custody of authorized staff.',
      pricingType: 'quote_based' as const,
      rateMin: null,
      rateMax: null,
      coverageHighlights: 'Cash in transit\nCash in safe\nCheques and negotiable instruments\nRobbery and hold-up\nCounterfeit notes (detection)',
      exclusions: 'Shortage discovered on audit\nEmployee dishonesty (use Fidelity)\nWar and terrorism\nElectronic transfers\nInadequate security',
      requiredDocuments: 'Business registration\nAverage weekly cash holding\nSafe specification\nSecurity arrangements',
      assetFields: [
        { key: 'cashInTransit', label: 'Maximum Cash Carried in Transit (₦)', type: 'number', required: true },
        { key: 'cashInSafe', label: 'Maximum Cash Held on Premises (₦)', type: 'number', required: true },
        { key: 'securityMeasures', label: 'Security Measures', type: 'text', required: false },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['money', 'cash', 'transit', 'safe', 'robbery', 'financial', 'business', 'cheque'],
    },
    {
      name: 'Group Life Assurance Scheme',
      category: 'Life',
      description: 'A single insurance contract paid for by an employer that pays a cash benefit to family members if a worker dies while still employed. Mandatory under the Pension Reform Act for businesses with three or more workers. The payout is at least three times the annual salary.',
      pricingType: 'calculable' as const,
      rate: 0.0006,
      calculationBasis: 'annual salary / sum assured',
      coverageHighlights: 'Death benefit (minimum 3x annual salary)\nAccidental death\nTotal permanent disability\nFuneral expenses benefit',
      exclusions: 'Suicide within first year\nWar and terrorism\nSelf-inflicted injury\nCriminal acts',
      requiredDocuments: 'Employee list with salaries\nBusiness registration\nPension compliance certificate',
      assetFields: [
        { key: 'numberOfEmployees', label: 'Number of Employees', type: 'text', required: true },
        { key: 'totalAnnualSalary', label: 'Total Annual Salary Bill (₦)', type: 'number', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['group life', 'life assurance', 'employer', 'employee', 'death benefit', 'pension', 'statutory', 'life insurance'],
    },
    {
      name: "Combined Workmen's Compensation / Group Personal Accident",
      category: 'Liability',
      description: 'A unified business insurance package protecting employers against statutory liabilities for workplace injuries while providing 24-hour worldwide accident and medical coverage for employees regardless of fault or duty hours.',
      pricingType: 'quote_based' as const,
      rateMin: null,
      rateMax: null,
      coverageHighlights: 'Workplace injury compensation\nAccidental death benefit\nPermanent disability\nTemporary total disability\nMedical expenses\n24-hour worldwide cover',
      exclusions: 'Pre-existing conditions\nSelf-inflicted injury\nWar and terrorism\nIntoxication\nAIDS/HIV',
      requiredDocuments: 'Employee list with job descriptions\nAnnual payroll\nBusiness registration\nSafety policies',
      assetFields: [
        { key: 'numberOfEmployees', label: 'Number of Employees', type: 'text', required: true },
        { key: 'annualPayroll', label: 'Annual Payroll (₦)', type: 'number', required: true },
        { key: 'industry', label: 'Industry / Nature of Work', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['workmen compensation', 'group personal accident', 'employer', 'employee', 'workplace', 'injury', 'accident', 'statutory'],
    },
    {
      name: 'Performance Bond',
      category: 'Financial',
      description: 'A surety bond issued by an insurance company ensuring a contractor completes a project according to its agreed terms, quality standards, and timelines. If the contractor fails to deliver, the insurer compensates the project owner for losses.',
      pricingType: 'quote_based' as const,
      rateMin: 0.006,
      rateMax: 0.01,
      coverageHighlights: 'Project completion guarantee\nContractor default protection\nQuality standard assurance\nTimeline compliance\nFinancial loss compensation',
      exclusions: 'Change of scope disputes\nForce majeure events\nClient-caused delays\nGovernment action',
      requiredDocuments: 'Contract documents\nContractor\'s financial statements\nProject details\nPrincipal\'s details',
      assetFields: [
        { key: 'contractValue', label: 'Contract Value (₦)', type: 'number', required: true },
        { key: 'bondAmount', label: 'Bond Amount Required (₦)', type: 'number', required: true },
        { key: 'projectDescription', label: 'Project Description', type: 'text', required: true },
        { key: 'contractDuration', label: 'Contract Duration (months)', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['performance bond', 'surety', 'contractor', 'project', 'guarantee', 'construction', 'bond'],
    },
    {
      name: 'Advance Payment Bond',
      category: 'Financial',
      description: 'A financial guarantee protecting a project owner or buyer if a contractor fails to use an upfront cash advance or mobilization deposit for its intended project, or goes bankrupt before doing the work.',
      pricingType: 'quote_based' as const,
      rateMin: 0.006,
      rateMax: 0.01,
      coverageHighlights: 'Mobilization advance protection\nContractor insolvency cover\nMisuse of advance funds\nProject owner financial protection',
      exclusions: 'Change in project scope\nGovernment action\nForce majeure\nClient default',
      requiredDocuments: 'Contract documents\nAdvance payment details\nContractor\'s financial statements\nProject timeline',
      assetFields: [
        { key: 'advanceAmount', label: 'Advance Payment Amount (₦)', type: 'number', required: true },
        { key: 'contractValue', label: 'Total Contract Value (₦)', type: 'number', required: true },
        { key: 'projectDescription', label: 'Project Description', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['advance payment', 'mobilization', 'bond', 'guarantee', 'contractor', 'surety', 'project'],
    },
    {
      name: 'Counter Indemnity Bond',
      category: 'Financial',
      description: 'A legal agreement where a business promises to repay the insurance company if the insurer has to pay a claim on a surety bond issued on that client\'s behalf. Acts as a safety backup for the insurer.',
      pricingType: 'quote_based' as const,
      rateMin: 0.006,
      rateMax: 0.01,
      coverageHighlights: 'Surety bond backing\nInsurer protection\nFinancial guarantee\nLegal obligation compliance',
      exclusions: 'Fraud by principal\nWilful default\nMisrepresentation',
      requiredDocuments: 'Original surety bond details\nFinancial statements\nBoard resolution',
      assetFields: [
        { key: 'bondAmount', label: 'Bond Amount (₦)', type: 'number', required: true },
        { key: 'bondDescription', label: 'Bond Description', type: 'text', required: true },
      ],
      durationMonths: 12,
      isActive: true,
      keywords: ['counter indemnity', 'surety', 'bond', 'guarantee', 'financial', 'insurer'],
    },
    {
      name: 'Health Insurance',
      category: 'Health',
      description: 'Pays for doctor visits, hospital stays, and medicines. Reduces your medical bills during illness or injury. Available for individuals, families, and corporate groups. Coverage and premiums vary by plan — request a quote for your specific needs.',
      pricingType: 'quote_based' as const,
      rateMin: null,
      rateMax: null,
      coverageHighlights: 'Outpatient consultation\nInpatient/hospital admission\nSurgery and specialist care\nMaternity cover\nPrescription drugs\nEmergency treatment',
      exclusions: 'Pre-existing conditions (waiting period applies)\nCosmetic procedures\nExperimental treatments\nSelf-inflicted injury\nDrug abuse',
      requiredDocuments: 'Completed proposal form\nMedical history declaration\nID document',
      assetFields: [],
      durationMonths: 12,
      isActive: true,
      keywords: ['health', 'medical', 'hospital', 'hmo', 'doctor', 'treatment', 'healthcare', 'maternity', 'surgery'],
    },
    {
      name: 'Travel Insurance',
      category: 'Travel',
      description: 'Covers medical emergencies, lost bags, and cancelled trips abroad. Essential for international travel including visa applications for Schengen, UK, USA, Canada, and other destinations.',
      pricingType: 'quote_based' as const,
      rateMin: null,
      rateMax: null,
      coverageHighlights: 'Emergency medical treatment abroad\nMedical evacuation\nTrip cancellation\nLost or delayed baggage\nFlight delays\nPersonal liability abroad\nPassport loss',
      exclusions: 'Pre-existing medical conditions (unless declared)\nAdventure sports (unless endorsed)\nWar zones\nSelf-inflicted injury\nAlcohol-related incidents',
      requiredDocuments: 'Valid passport\nTravel itinerary\nVisa application details',
      assetFields: [
        { key: 'destination', label: 'Destination Country/Region', type: 'text', required: true },
        { key: 'departureDate', label: 'Departure Date', type: 'text', required: true },
        { key: 'returnDate', label: 'Return Date', type: 'text', required: true },
        { key: 'numberOfTravellers', label: 'Number of Travellers', type: 'text', required: true },
        { key: 'travelPurpose', label: 'Purpose of Travel', type: 'select', options: ['Tourism/Holiday', 'Business', 'Study', 'Medical', 'Family visit'], required: true },
      ],
      durationMonths: 1,
      isActive: true,
      keywords: ['travel', 'holiday', 'visa', 'schengen', 'abroad', 'trip', 'vacation', 'international', 'dubai', 'uk', 'usa'],
    },
  ];

  let created = 0;
  let updated = 0;

  for (const product of products) {
    const item = product as Record<string, unknown>;
    const keywords = (item.keywords as string[] | undefined) ?? CATEGORY_KEYWORDS[item.category as string] ?? [];
    const status = item.isActive === false ? 'inactive' : 'active';
    const data = {
      name: item.name as string,
      category: item.category as string,
      description: item.description as string,
      pricingType: item.pricingType as string,
      premiumAmount: item.premiumAmount ?? null,
      rate: item.rate ?? null,
      rateMin: item.rateMin ?? null,
      rateMax: item.rateMax ?? null,
      calculationBasis: item.calculationBasis ?? null,
      assetFields: item.assetFields ?? null,
      durationMonths: (item.durationMonths as number) ?? 12,
      coverageHighlights: item.coverageHighlights as string,
      exclusions: item.exclusions as string,
      requiredDocuments: item.requiredDocuments as string,
      keywords,
      status,
    };

    const existing = await prisma.product.findFirst({
      where: { name: item.name as string },
    });

    if (existing) {
      await prisma.product.update({
        where: { id: existing.id },
        data: data as never,
      });
      updated += 1;
    } else {
      await prisma.product.create({ data: data as never });
      created += 1;
    }
  }

  const seededNames = products.map((p) => p.name);
  const deactivated = await prisma.product.updateMany({
    where: {
      name: { notIn: seededNames },
      status: 'active',
    },
    data: { status: 'inactive' },
  });

  console.log(`Seeded ${products.length} products (${created} created, ${updated} updated, ${deactivated.count} deactivated)`);

  console.log('Seed complete');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
