const SYNONYMS: Record<string, string[]> = {
  car: ['motor', 'vehicle', 'automobile', 'auto', 'motorbike', 'motorcycle'],
  vehicle: ['motor', 'car', 'automobile', 'auto', 'truck', 'bus'],
  automobile: ['motor', 'car', 'vehicle'],
  auto: ['motor', 'car', 'vehicle'],
  motorbike: ['motor', 'motorcycle', 'bike', 'vehicle'],
  motorcycle: ['motor', 'motorbike', 'bike', 'vehicle'],
  truck: ['motor', 'vehicle', 'haulage', 'commercial'],
  bus: ['motor', 'vehicle', 'commercial', 'transport'],
  bike: ['motor', 'vehicle', 'motorcycle', 'motorbike'],
  driving: ['motor', 'vehicle', 'road'],
  accident: ['motor', 'health', 'claim', 'collision', 'personal accident'],
  crash: ['motor', 'accident', 'collision', 'vehicle'],
  collision: ['motor', 'accident', 'crash'],
  theft: ['motor', 'property', 'burglary', 'stolen'],
  stolen: ['theft', 'motor', 'property', 'burglary'],
  'third party': ['motor', 'liability', 'tpft'],
  tpft: ['motor', 'third party', 'liability'],
  comprehensive: ['motor', 'full cover', 'vehicle'],
  'car insurance': ['motor'],
  'vehicle insurance': ['motor'],
  'auto insurance': ['motor'],
  'motor policy': ['motor'],
  'cheap car insurance': ['motor'],
  'best car insurance': ['motor'],
  'renew car insurance': ['motor', 'renewal'],
  'new car': ['motor'],
  'used car': ['motor'],
  'imported car': ['motor'],
  'car accident': ['motor', 'health'],
  'car theft': ['motor', 'theft'],
  'car fire': ['motor', 'property', 'fire'],
  'vehicle damage': ['motor'],
  compulsory: ['motor', 'third party'],
  holiday: ['travel', 'trip', 'vacation', 'abroad'],
  vacation: ['travel', 'holiday', 'trip', 'abroad'],
  trip: ['travel', 'holiday', 'vacation', 'abroad'],
  abroad: ['travel', 'international', 'overseas', 'foreign'],
  overseas: ['travel', 'abroad', 'international'],
  international: ['travel', 'abroad', 'overseas'],
  flight: ['travel', 'airline', 'aviation'],
  luggage: ['travel', 'baggage', 'suitcase'],
  baggage: ['travel', 'luggage', 'suitcase'],
  passport: ['travel', 'abroad', 'international'],
  visa: ['travel', 'abroad', 'international', 'schengen'],
  schengen: ['travel', 'visa', 'europe', 'abroad'],
  tourist: ['travel', 'holiday', 'vacation'],
  journey: ['travel', 'trip', 'abroad'],
  dubai: ['travel', 'abroad', 'international'],
  london: ['travel', 'abroad', 'international', 'uk'],
  usa: ['travel', 'abroad', 'international'],
  uk: ['travel', 'abroad', 'international'],
  europe: ['travel', 'abroad', 'schengen', 'international'],
  canada: ['travel', 'abroad', 'international'],
  turkey: ['travel', 'abroad', 'international'],
  'travel insurance': ['travel'],
  'holiday insurance': ['travel'],
  'trip insurance': ['travel'],
  'travel medical': ['travel', 'health'],
  'lost luggage': ['travel'],
  'lost baggage': ['travel'],
  'flight cancelled': ['travel'],
  'medical while travelling': ['travel', 'health'],
  'overseas medical': ['travel', 'health'],
  hospital: ['health', 'medical', 'hmo'],
  medical: ['health', 'hospital', 'treatment', 'hmo'],
  doctor: ['health', 'medical', 'hospital'],
  illness: ['health', 'medical', 'sickness'],
  sickness: ['health', 'medical', 'illness'],
  treatment: ['health', 'medical', 'hospital'],
  surgery: ['health', 'medical', 'hospital'],
  hmo: ['health', 'medical', 'hospital'],
  medicine: ['health', 'medical', 'pharmacy'],
  clinic: ['health', 'medical', 'hospital'],
  maternity: ['health', 'medical', 'hospital'],
  dental: ['health', 'medical'],
  'eye care': ['health', 'medical'],
  healthcare: ['health', 'medical', 'hmo'],
  'hospital bills': ['health', 'medical'],
  'medical bills': ['health', 'medical'],
  'family health': ['health'],
  'health plan': ['health'],
  'private health': ['health'],
  outpatient: ['health', 'medical'],
  inpatient: ['health', 'medical', 'hospital'],
  pharmacy: ['health', 'medical'],
  death: ['life', 'funeral', 'beneficiary'],
  funeral: ['life', 'death', 'burial'],
  burial: ['life', 'death', 'funeral'],
  beneficiary: ['life', 'death', 'family'],
  nominee: ['life', 'beneficiary', 'family'],
  'life cover': ['life'],
  'life assurance': ['life'],
  'family protection': ['life', 'health'],
  'financial protection': ['life'],
  endowment: ['life', 'savings', 'investment'],
  'education insurance': ['life'],
  'children education': ['life', 'health'],
  retirement: ['life', 'savings'],
  'wealth protection': ['life', 'financial'],
  'estate protection': ['life'],
  'income protection': ['life'],
  'what happens if i die': ['life'],
  'protect my family': ['life', 'health'],
  house: ['property', 'building', 'home', 'real estate'],
  home: ['property', 'building', 'house', 'real estate'],
  building: ['property', 'house', 'construction', 'real estate'],
  office: ['property', 'commercial', 'building', 'sme'],
  shop: ['property', 'commercial', 'retail', 'sme'],
  fire: ['property', 'engineering', 'fire and special perils'],
  flood: ['property', 'natural disaster', 'water damage'],
  burglary: ['property', 'theft', 'stolen', 'break in'],
  landlord: ['property', 'rent', 'tenant'],
  tenant: ['property', 'rent', 'landlord'],
  'real estate': ['property', 'building', 'house'],
  contents: ['property', 'home', 'household'],
  household: ['property', 'home', 'contents'],
  storm: ['property', 'natural disaster'],
  'accidental damage': ['property', 'motor'],
  'property damage': ['property', 'motor', 'liability'],
  'building damage': ['property'],
  'house fire': ['property', 'fire'],
  'home contents': ['property'],
  renters: ['property', 'tenant'],
  'homeowners insurance': ['property'],
  ship: ['marine', 'cargo', 'sea', 'vessel'],
  boat: ['marine', 'sea', 'vessel', 'water'],
  vessel: ['marine', 'ship', 'boat', 'sea'],
  cargo: ['marine', 'freight', 'goods', 'shipping'],
  shipping: ['marine', 'cargo', 'freight', 'sea'],
  freight: ['marine', 'cargo', 'shipping', 'goods'],
  sea: ['marine', 'ocean', 'water', 'vessel'],
  ocean: ['marine', 'sea', 'water'],
  import: ['marine', 'cargo', 'freight', 'shipping'],
  export: ['marine', 'cargo', 'freight', 'shipping'],
  goods: ['marine', 'cargo', 'freight', 'transit', 'goods in transit'],
  transit: ['marine', 'cargo', 'goods in transit'],
  'goods in transit': ['marine', 'cargo', 'transit'],
  'marine cargo': ['marine'],
  'transporting goods': ['marine', 'goods in transit'],
  'goods damaged': ['marine', 'goods in transit'],
  'goods transported': ['marine', 'goods in transit'],
  machinery: ['engineering', 'equipment', 'plant', 'industrial'],
  equipment: ['engineering', 'machinery', 'plant'],
  construction: ['engineering', 'building', 'contractor', 'property'],
  contractor: ['engineering', 'construction', 'project'],
  factory: ['engineering', 'industrial', 'plant', 'machinery'],
  industrial: ['engineering', 'factory', 'plant', 'machinery'],
  plant: ['engineering', 'machinery', 'factory'],
  breakdown: ['engineering', 'machinery', 'equipment'],
  erection: ['engineering', 'construction', 'installation'],
  'contractors all risks': ['engineering', 'construction'],
  'electronic equipment': ['engineering', 'equipment'],
  'machinery breakdown': ['engineering', 'machinery'],
  'building project': ['engineering', 'construction', 'property'],
  fraud: ['financial', 'fidelity', 'bond'],
  fidelity: ['financial', 'fraud', 'bond'],
  bond: ['financial', 'fidelity', 'guarantee'],
  'professional indemnity': ['financial', 'liability', 'professional'],
  'directors officers': ['financial', 'liability'],
  'employee stole': ['financial', 'fidelity'],
  'money stolen': ['financial', 'fidelity', 'money insurance'],
  'business money': ['financial', 'money insurance'],
  liability: ['liability', 'public', 'employer', 'third party'],
  'public liability': ['liability', 'public', 'third party'],
  employer: ['liability', 'workmen', 'employee', 'staff'],
  workmen: ['liability', 'employer', 'compensation', 'worker'],
  compensation: ['liability', 'workmen', 'employer'],
  injury: ['liability', 'health', 'accident', 'workmen'],
  'customer injured': ['liability', 'public liability'],
  'employee injured': ['liability', 'workmen'],
  'legal claims': ['liability'],
  'legal responsibility': ['liability'],
  farm: ['agriculture', 'crop', 'livestock', 'farmer'],
  farmer: ['agriculture', 'farm', 'crop', 'livestock'],
  crop: ['agriculture', 'farm', 'harvest', 'plant'],
  livestock: ['agriculture', 'farm', 'cattle', 'poultry'],
  cattle: ['agriculture', 'livestock', 'farm'],
  poultry: ['agriculture', 'livestock', 'farm', 'chicken'],
  fish: ['agriculture', 'aquaculture', 'farm'],
  harvest: ['agriculture', 'crop', 'farm'],
  rural: ['agriculture', 'farm', 'crop'],
  business: ['sme', 'commercial', 'company', 'enterprise'],
  sme: ['business', 'commercial', 'small business'],
  company: ['business', 'sme', 'commercial'],
  restaurant: ['business', 'sme', 'commercial', 'property'],
  warehouse: ['business', 'sme', 'property', 'commercial'],
  'small business': ['sme', 'business', 'commercial'],
  'business interruption': ['sme', 'business', 'commercial'],
  'business theft': ['sme', 'property', 'theft'],
  'business fire': ['sme', 'property', 'fire'],
  insurance: ['cover', 'coverage', 'protection', 'policy', 'plan', 'assurance'],
  cover: ['insurance', 'coverage', 'protection', 'policy'],
  coverage: ['insurance', 'cover', 'protection', 'policy'],
  protection: ['insurance', 'cover', 'coverage', 'policy'],
  policy: ['insurance', 'cover', 'plan', 'protection'],
  plan: ['insurance', 'policy', 'cover'],
  assurance: ['insurance', 'cover', 'life'],
  premium: ['price', 'cost', 'payment', 'insurance fee'],
  price: ['premium', 'cost', 'payment'],
  cost: ['premium', 'price', 'payment'],
  claim: ['request payment', 'report loss', 'report accident', 'compensation', 'payout'],
  payout: ['claim', 'compensation', 'payment'],
  renewal: ['renew', 'extend', 'continue cover'],
  renew: ['renewal', 'extend', 'continue'],
  excess: ['deductible', 'claim contribution'],
  deductible: ['excess', 'claim contribution'],
  exclusion: ['not covered', 'excluded'],
  'not covered': ['exclusion', 'excluded'],
};

const INTENT_PHRASES: Record<string, string[]> = {
  'i need insurance for my car': ['motor'],
  'i need insurance for my vehicle': ['motor'],
  'i need insurance for my family': ['life', 'health'],
  'i need insurance for my children': ['life', 'health'],
  'i need insurance for my parents': ['health', 'life'],
  'i need insurance for my trip': ['travel'],
  'i need insurance for my house': ['property'],
  'i need insurance for my home': ['property'],
  'i need insurance for my shop': ['sme', 'property'],
  'i need insurance for my business': ['sme'],
  'i need insurance for my employees': ['liability'],
  'i need insurance for my goods': ['marine', 'goods in transit'],
  'i need insurance for my building': ['property', 'engineering'],
  'i need insurance for my equipment': ['engineering'],
  'i want protection against accident': ['motor', 'health'],
  'i want protection against theft': ['motor', 'property'],
  'i want protection against fire': ['property', 'engineering'],
  'i want protection against flood': ['property'],
  'i want protection against medical bills': ['health'],
  'i want protection against death': ['life'],
  'i want protection against travel emergencies': ['travel'],
  'i want protection against legal claims': ['liability'],
  'my goods are being transported': ['marine', 'goods in transit'],
  'someone stole money from my business': ['financial', 'money insurance'],
  'an employee stole from my business': ['financial', 'fidelity'],
  'a customer got injured in my shop': ['liability', 'public liability'],
  'my employee got injured at work': ['liability', 'workmen'],
  'my building caught fire': ['property', 'fire and special perils'],
  'my house was burgled': ['property', 'burglary'],
  'my goods were damaged during transportation': ['marine', 'goods in transit'],
  'my business had to close because of damage': ['sme', 'business interruption'],
  'my expensive equipment was damaged': ['engineering'],
  'i need insurance for construction': ['engineering', 'contractors all risks'],
  'i am transporting goods by sea': ['marine'],
  'protect my car': ['motor'],
  'protect my house': ['property'],
  'protect my family': ['life', 'health'],
  'protect my business': ['sme'],
  'insurance for visa': ['travel'],
  'insurance for travelling': ['travel'],
  'insurance before travelling': ['travel'],
};

function expandSearchTerms(input: string): string[] {
  const term = input.toLowerCase().trim();
  if (term.length < 2) return [term];

  const words = term.split(/\s+/).filter(Boolean);
  const expanded = new Set<string>();

  expanded.add(term);

  for (const [phrase, categories] of Object.entries(INTENT_PHRASES)) {
    if (term.includes(phrase) || phrase.includes(term)) {
      categories.forEach((c) => expanded.add(c));
    }
  }

  for (const word of words) {
    expanded.add(word);

    const exactSynonyms = SYNONYMS[word] || [];
    exactSynonyms.forEach((s) => expanded.add(s));

    for (const [phrase, synonyms] of Object.entries(SYNONYMS)) {
      if (phrase.startsWith(word) || word.startsWith(phrase)) {
        expanded.add(phrase);
        synonyms.forEach((s) => expanded.add(s));
      }
    }
  }

  for (const [phrase, synonyms] of Object.entries(SYNONYMS)) {
    if (term.includes(phrase) || phrase.startsWith(term)) {
      synonyms.forEach((s) => expanded.add(s));
    }
  }

  return Array.from(expanded);
}

export { SYNONYMS, INTENT_PHRASES, expandSearchTerms };
